server:
  port: 10010
spring:
  application:
    name: leyou-gateway
eureka:
  client:
    service-url:
     defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 5
zuul:
  prefix: /api
  routes:
   item-service: /item/** #路由到商品的微服务 跨域 需要加域名
   search-service: /search/** #路由到搜索微服务
   user-service: /user/**
   auth-service: /auth/**
   cart-service: /cart/**
   order-service: /order/**
   seckill-service: /seckill/**
  add-host-header: true #携带域名 解决domain
  sensitive-headers: #覆盖 默认的禁用的头信息
leyou:
  jwt:
    pubKeyPath: D:/heima30/rsa/rsa.pub # 公钥地址
    cookieName: LY_TOKEN
  filter: #白名单
    allowPaths:
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item
      - /api/order
      - /api/seckill



