server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://localhost:3306/test2?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  cloud: #防止循环引用 data
   refresh:
    refreshable: none
  rabbitmq:
    host: 192.168.128.128
    virtual-host: /leyou
    username: leyou
    password: leyou
    template:
      exchange: LEYOU.ITEM.EXCHANGE  #默认使用配置好的交换机
eureka:
  client:
    service-url:
     defaultZone: http://localhost:10086/eureka
  instance:
   lease-expiration-duration-in-seconds: 15
   lease-renewal-interval-in-seconds: 5
mybatis:
  type-aliases-package: com.leyou.item.pojo #需要在项目中依赖pojo所在项目
leyou:
  jwt:
    pubKeyPath: D:/heima30/rsa/rsa.pub # 公钥地址
    cookieName: LY_TOKEN