server:
  port: 10000
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.128.128
    virtual-host: /leyou
    username: leyou
    password: leyou
leyou:
  sms:
    accessKeyId: LTAI4FsRjXg44HVc3kVpHdU2 # 你自己的accessKeyId
    accessKeySecret: u4vH3TLZUuN2wSAQsB3jaNicnYTzZJ # 你自己的AccessKeySecret
    signName: LBW # 签名名称
    verifyCodeTemplate: SMS_175480182 # 模板名称