server:
  port: 8090
spring:
  application:
    name: seckill-service
  redis:
      host: 192.168.128.128
  datasource:
    url: jdbc:mysql://localhost:3306/test2?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  cloud: #防止循环引用 data
   refresh:
    refreshable: none
  rabbitmq:
    host: 192.168.128.128
    virtual-host: /leyou
    username: leyou
    password: leyou
    template:
      exchange: LEYOU.ITEM.EXCHANGE  #默认使用配置好的交换机
eureka:
  client:
    service-url:
     defaultZone: http://localhost:10086/eureka
  instance:
   lease-expiration-duration-in-seconds: 15
   lease-renewal-interval-in-seconds: 5
mybatis:
  type-aliases-package: com.leyou.seckill.pojo #需要在项目中依赖pojo所在项目
ly:
  worker:
    workerId: 1
    datacenterId: 1
  jwt:
    pubKeyPath: D:/heima30/rsa/rsa.pub # 公钥地址
    cookieName: LY_TOKEN # cookie的名称
  pay:
    appId: wx8397f8696b538317
    mchId: 1473426802
    key: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb
    connectTimeoutMs: 5000
    readTimeoutMs: 10000